baseURL = "https://your-netlify-site.netlify.app"
languageCode = "en-us"
title = "TEDx Nijmegen"
theme = "default"  # Replace with your theme if needed

[params]
  description = "TEDx Nijmegen website powered by Hugo and Netlify CMS"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Speakers"
  url = "/speakers/"
  weight = 2

[[menu.main]]
  name = "Partners"
  url = "/partners/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
